# Generated by Django 3.0 on 2021-07-04 11:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('about_text_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='')),
                ('carousel_logo_slider', models.ImageField(upload_to='')),
                ('carousel_title', models.CharField(blank=True, max_length=100)),
                ('carousel_sub_title', models.CharField(max_length=100)),
                ('carousel_action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('faq_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('faq_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('faq_text_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('privacy_policy_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('privacy_policy_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('privacy_policy_text_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shipping_returns_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('shipping_returns_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('shipping_returns_text_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms_of_use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('terms_of_use_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('terms_of_use_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('terms_of_use_text_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
